import {
  CheckCircle2,
  ArrowDown,
  Target,
} from "lucide-react";

const roadmap = [
  "HTML",
  "CSS",
  "JavaScript",
  "React.js",
  "Node.js",
  "MongoDB",
  "Projects",
  "Placement Ready",
];

export default function RoadmapPreview() {
  return (
    <section
      id="roadmap"
      className="py-28"
    >
      <div className="mx-auto max-w-6xl px-6">

        {/* Heading */}

        <div className="text-center">

          <span className="rounded-full border border-indigo-500/30 bg-indigo-500/10 px-5 py-2 text-sm text-indigo-300">
            ROADMAP
          </span>

          <h2 className="mt-6 text-5xl font-bold text-white">
            Your AI Learning Roadmap
          </h2>

          <p className="mx-auto mt-6 max-w-3xl text-lg text-gray-400">
            Follow a personalized roadmap generated by AI to
            become placement-ready step by step.
          </p>

        </div>

        {/* Roadmap */}

        <div className="mt-20 flex flex-col items-center">

          <div className="mb-8 flex items-center gap-3 rounded-full bg-indigo-500/10 px-8 py-4">

            <Target className="text-indigo-400" />

            <span className="text-xl font-semibold text-white">
              Become a Full Stack Developer
            </span>

          </div>

          {roadmap.map((step, index) => (
            <div
              key={step}
              className="flex flex-col items-center"
            >

              <div className="group flex w-80 items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-6 py-5 transition-all duration-300 hover:scale-105 hover:border-indigo-500 hover:bg-indigo-500/10">

                <div className="flex items-center gap-4">

                  <CheckCircle2
                    className="text-green-400"
                    size={24}
                  />

                  <span className="text-lg font-medium text-white">
                    {step}
                  </span>

                </div>

                <span className="text-sm text-green-400">
                  Completed
                </span>

              </div>

              {index !== roadmap.length - 1 && (
                <ArrowDown
                  size={28}
                  className="my-4 text-indigo-500"
                />
              )}

            </div>
          ))}

        </div>

      </div>
    </section>
  );
}